
spring:
  application:
    name: ouro-gourmet
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
      enabled: true
      locations: classpath:db/migration
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
    groups-order: DESC
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui
    title: FIAP - Ouro Gourmet

server:
  port: 8081